### ISSUE TITLE
Run through Go-live-checklist

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgovdrupal.org#34]
See https://dev.docs.agile.coop/docs/processes/dev-go-live/

### Project tasks

- [x] Configure Metatags
- [x] Configure XML sitemap
- [x] Add a favicon         A recommended favicon generator is https://realfavicongenerator.net.        Favicons should be placed in the web root and linked to from html.html.twig    
- [x] Set up EU Cookie Compliance module
- [x] Create / Theme 404 and 403 pages
- [ ] Review / Theme maintenance page
- [ ] Discuss having Agile Collective page on the site
- [ ] If using config split (most new D8 sites) disable development modules by adding the following line to production's (and stage if you want) settings.local.php file: ```$config['config_split.config_split.development']['status'] = FALSE;```
- [x] Discuss HTTPS with the sysadmin and put a plan in place before the site launches

### Launch tasks

- [ ] Make sure site redirects to a single domain (with or without 'www')
- [x] Remove all dummy / test content including users. Search users and content for keywords such as "test" or "example".
- [x] Check spam protection is in place for public forms (if required - reCAPTCHA is what is being used as of March 2018)
- [x] Check access to content types and taxonomy term pages - use Rabbit Hole if necessary.
- [x] Check that the stage site and prod site point to the correct databases
- [x] drush status
- [x] Make sure the default site location is set to the live site address NOT staging.sitename.com.
- [x] Ensure the site email address is set to something sensible e.g. noreply@site-domain.com (/admin/config/system/site-information)
- [x] Check the contents of the site emails is sane.
- [x] Check any API keys are configured for the live domain. E.g. GA, Recaptcha, Payment gateways
- [x] Check indexing status for Search API - check if this is set to 'index immediately' or not - ideally it would not be, for performance reasons.
- [x] Make sure URL redirects are set up to automatically add a redirect when the page title is changed
- [x] Check the site has a Privacy Policy / cookie warning
- [x] Install the Purge module and integrate it with Varnish. Set up and configuration guide.

### Performance

- [x]  Enable Drupal caching and asset aggregation at Configuration > Development > Performance (/admin/config/development/performance). Set the max page cache age to at least 3 hours and aggregate CSS and JavaScript files.
- [ ]  Set JPEG quality to no higher than 75% (/admin/config/media/image-toolkit)
- [ ]  Consider using the AdvAgg module for greater control of caching and aggregation of assets; https://www.drupal.org/project/advagg

**Comment by msayoung** [comment]
@finnlewis  this is done now I think?
